import SearchIcon from "@mui/icons-material/Search";

export const BooksData = [
    {
        name:"book name",
        type:"text",
        placeholder:"book name",
        id:"search",
        width:"100%",
        margin:"0px",
        padding:"8px 16px",
        borderRadius:"5px",
        border:"1px solid #ccc",
        bgColor:"",
        color:"#5b5a5a",
        fontSize:"16px",
        lable:"search",
    },
    {
        name:"book name",
        type:"text",
        placeholder:"book name",
        id:"search",
        width:"100%",
        margin:"0px",
        padding:"8px 16px",
        borderRadius:"5px",
        border:"1px solid #ccc",
        bgColor:"",
        color:"#5b5a5a",
        fontSize:"16px",
        lable:"search",
    },
    {
        name:"book name",
        type:"text",
        placeholder:"book name",
        id:"search",
        width:"100%",
        margin:"0px",
        padding:"8px 16px",
        borderRadius:"5px",
        border:"1px solid #ccc",
        bgColor:"",
        color:"#5b5a5a",
        fontSize:"16px",
        lable:"search",
    },
    {
        name:"book name",
        type:"text",
        placeholder:"book name",
        id:"search",
        width:"100%",
        margin:"0px",
        padding:"8px 16px",
        borderRadius:"5px",
        border:"1px solid #ccc",
        bgColor:"",
        color:"#5b5a5a",
        fontSize:"16px",
        lable:"search",
    },
    {
        name:"search",
        type:"text",
        placeholder:"book name",
        id:"search",
        width:"100%",
        margin:"0px",
        padding:"8px 16px",
        borderRadius:"5px",
        border:"1px solid #ccc",
        bgColor:"",
        color:"#5b5a5a",
        fontSize:"16px",
        lable:"search",
    },
];
