export const BooksData = [
  {
    name: "bookname",
    type: "text",
    placeholder: "Book name",
    id: "Book",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderradius: "5px",
    border: "1px solid #ccc",
    bgcolor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Book name",
    className: 'bookName'
  },
  {
    name: "author",
    type: "text",
    placeholder: "author",
    id: "author",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderradius: "5px",
    border: "1px solid #ccc",
    bgColor: "",
    color: "#5b5a5a",
    fontsize: "16px",
    lable: "author",
    className: 'author'
  },
  {
    name: "publisher",
    type: "text",
    placeholder: "Publisher",
    id: "publisher",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderradius: "5px",
    border: "1px solid #ccc",
    bgcolor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Publisher",
    className: 'publisher',
  },
  {
    name: "numberofpages",
    type: "text",
    placeholder: "Number of pages",
    id: "number",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderradius: "5px",
    border: "1px solid #ccc",
    bgcolor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Number of pages",
    className: 'number-of-pages',
  },
];
