export const BooksData = [
  {
    name: "bookName",
    type: "text",
    placeholder: "Book name",
    id: "Book",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    bgColor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Book name",
    inputClass: 'bookName'
  },
  {
    name: "author",
    type: "text",
    placeholder: "author",
    id: "author",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    bgColor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "author",
    inputClass: 'author'
  },

  {
    name: "publisher",
    type: "text",
    placeholder: "Publisher",
    id: "publisher",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    bgColor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Publisher",
    inputClass: 'publisher',
  },
  {
    name: "numberOfPages",
    type: "text",
    placeholder: "Number of pages",
    id: "number",
    width: "100%",
    margin: "0px",
    padding: "8px 5px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    bgColor: "",
    color: "#5b5a5a",
    fontSize: "16px",
    lable: "Number of pages",
    inputClass: 'number-of-pages',
  },
];
